
cloud:
  aws:
    s3:
      bucket: "MerakiplaceImages"

    credentials:
      access-key: {aws_access_key_id}
      secret-key: {aws_secret_access_key_id}

    stack:
      auto: false

    region:
      static: {aws_region_static}


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8081